//
// Created by sanga on 02/04/2023.
//
#include <stdio.h>
#include <unistd.h>

int do_putchar(int c) {
    write(2, &c, 1);
    return 0;
}

// Write a function that prints the alphabet, in lowercase, followed by a new line.
void print_alphabet() {
    int i;
    i = 97;
    while (i <= 122) {
        do_putchar(i);
        i++;
    }
    do_putchar('\n');
}

// Write a function that prints 10 times the alphabet, in lowercase, followed by a new line.
void print_alphabet_x10() {
    int count, letter;
    count = 0;

    for (; count <= 9; count++) {
        letter = 97;
        while (letter <= 122) {
            do_putchar(letter);
            letter++;
        }
        do_putchar('\n');
    }
}

// Write a function that checks for lowercase character.
int do_islower(int c) {

    if (c >= 97 && c <= 122)
        return 1;
    else
        return 0;
}

// Write a function that checks for alphabetic character.
int do_isalpha(int c) {

    if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')) {
        return 1;
    } else {
        return 0;
    }
}

// Write a function that prints the sign of a number.
int print_sign(int n) {

    if (n > 0) {
        do_putchar('+');
        return 1;
    } else if (n == 0) {
        do_putchar('0');
        return 0;
    } else {
        do_putchar('-');
        return -1;
    }
}

// Write a function that computes the absolute value of an integer.
int do_abs(int n) {

    // TODO: please note that zero is a positive number
    if (n < 0)
        n = -n;
    else
        n = n;
    return n;
}

// Write a function that prints the last digit of a number.
int print_last_digit(int n) {

    if (n < 0) {
        do_putchar('0' - (n % 10));
        return -1 * (n % 10);
    } else {
        do_putchar('0' + (n % 10));
        return n % 10;
    }
}

// Write a function that prints every minute of the day of Jack Bauer, starting from 00:00 to 23:59.
void jack_bauer() {
    int hours, minutes;

    for (hours = 0; hours < 24; hours++) {
        for (minutes = 0; minutes < 60; minutes++) {
            printf("%02d:%02d\n", hours, minutes);
        }
    }
}

// Write a function that adds two integers and returns the result.
int add(int a, int b) {
    return a + b;
}

/**
* If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
 * The sum of these multiples is 23. Write a program that computes and prints the sum of all the multiples of 3 or 5 below 1024 (excluded), followed by a new line.
*/
int natural_sum35() {
    int i;
    i = 1;
    int sum = 0;
    for (; i < 1024; i++) {
        if (i % 3 == 0 || i % 5 == 0) {
            sum += i;
        }
    }
    printf("%d\n", sum);
    return 0;

}
/**
 * Write a function that prints all natural numbers from n to 98, followed by a new line.
 * Numbers must be separated by a comma, followed by a space
 * Numbers should be printed in order The first printed number should be the number passed to your function
 * The last printed number should be 98. You are allowed to use the standard library
 */
void print_to_98(int n){
    int i;
    if (n <= 98){
        for (; n <= 97; n++){
            printf("%d, ", n);
        }
    }

    else{
     for (i = n; i > 98; i--){
         printf("%d, ", i);
     }
    }
    printf("98\n");
}

// Write a program that prints the first 50 Fibonacci numbers, starting with 1 and 2, followed by a new line.
int fib1() {
    long i, n = 10, temp;
    long num1 = 1, num2 = 2;
    for (i = 0; i < n; i++) {

        if (num1 != 20365011074) {
            printf("%ld, ", num1);
        } else {
            printf("%ld\n", num1);
        }
        temp = num1 + num2; // Add the first and second numbers and swap
        num1 = num2;
        num2 = temp;
    }
    return 0;
}

/**
* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
* By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.
* By considering the terms in the Fibonacci sequence whose values do not exceed 4,000,000, write a program that finds
* and prints the sum of the even-valued terms, followed by a new line.
*/
int fib2(){

    long num1 = 1, num2 = 2;
    long n = 4000000, sum = 0;

    while (num2 <=n){
        if (num2 % 2 ==0 ){
            sum +=num2;
        }
        int temp;
        temp = num1 + num2;
        num1 = num2;
        num2 =temp;
    }
    printf("%ld ", sum);
    return 0;
}